biomixer_interface/back_end/urls.py
from django.urls import path

from . import views

app_name = 'back_end'
urlpatterns = [
    path(
        '',
        views.HomePage.as_view(),
        name='home',
    ),
    path(
        'library/',
        views.LibraryPage.as_view(),
        name='library',
    ),
    path(
        'mixing/',
        views.MixingPage.as_view(),
        name='mixing',
    ),
    path(
        'preparing/',
        views.PreparingPage.as_view(),
        name='preparing',
    ),
    path(
        'connect/',
        views.QRConnect.as_view(),
        name='connect'
    ),
    path(
        'dzone/',
        views.DropZone.as_view(),
        name='dzone'
    ),
    path(
        'file-upload',
        views.DropZone.as_view(),
        name='file_upload'
    ),
    path(
        'dzone_success',
        views.DropZone.success,
        name='dzone_succes'
    ),
    path(
        'api_materiom',
        views.DropZone.success,
        name='api_materiom'
    ),
    path(
        'api_materiom_query',
        views.DropZone.success,
        name='api_materiom_query'
    ),
    path(
        'dzone_success',
        views.DropZone.success,
        name='dzone_succes'
    ),
    path(
        'machine_output',
        views.LiveOutputs.txt,
        name='machine_output'
    ),
    path(
        'recipe',
        views.RecipePage.as_view(),
        name='recipe'
    ),
    path(
        'machine_controller',
        views.MachineController.as_view(),
        name='machine_controller'
    )


]

biomixer_interface/biomixer_interface/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('back_end.urls', namespace="back_end")),
    path('react/', TemplateView.as_view(template_name='index.html'))
]

urlpatterns += static(settings.MEDIA_URL, documet_root=settings.MEDIA_ROOT)

biomixer_interface/back_end/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone


# Create your models here.
class Doc(models.Model):
    upload = models.FileField(upload_to='recipes/')

    def __str__(self):
        return str(self.pk)


class Recipe(models.Model):
    """
        An additive recipe of biomaterials
    """
    name = models.CharField(max_length=100)
    tag = models.CharField(max_length=100)
    img_link = models.URLField()
    creation_date = models.DateField(default=timezone.now())

    def __str__(self):
        return self.name


class Step(models.Model):
    """
        List of materials and its Quantities
        used in a recipe
    """
    recipe_id = models.ForeignKey(Recipe, on_delete=models.RESTRICT)
    text = models.CharField(max_length=100)


class Material(models.Model):
    """
        Material used in a step recipe.
    """
    class Types(models.TextChoices):
        CARBOHIDRATES = 'CH', _('Carbohidrates')
        PROTEINS = 'PR', _('Proteins')
        MINERALS = 'MN', _('Minerals')
        LIPIDS = 'LP', _('Lipids')
        RESINS = 'RS', _('Resins')
        PHENOLICS = 'PH', _('Phenolics')
        NATURAL_COMPOSITES = 'NC'

    type = models.CharField(
        max_length=2,
        choices=Types.choices
    )
    name = models.CharField(max_length=200)
    chemical_formula = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Supply(models.Model):
    """
        Material and it's order in a recipe \n
        @:attribute recipe: Recipe to which it belongs the current supply \n
        @:param material: Material used in this supply \n
        @:param position: Order in which materials are placed
    """
    class Types(models.TextChoices):
        GRAMS = 'g', _('Grams')
        MILILITERS = 'ml', _('Milliliters')

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    position = models.IntegerField()
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    value = models.IntegerField()
    type = models.CharField(
        max_length=20,
        choices=Types.choices)

biomixer_interface/back_end/forms.py
from django import forms
from django.forms import formset_factory, BaseFormSet
from .models import *


# Labels for forms
class Labels:
    options = ['Support', 'Plasticizer', 'Binder', 'Preservative', 'Organic Waste']
    index = 0

    @property
    def get_label(self):
        current_index = self.index
        self.index += 1
        return self.options[current_index]


class MaterialForm (forms.Form):
    material = forms.ModelChoiceField(label='Material',
                                      required=True,
                                      widget=forms.Select(
                                          attrs={
                                              'class': 'col-3 mr-4 custom-select d-block',
                                              'placeholder': 'Choose Material'
                                          }),
                                      queryset=Material.objects.all())
    value = forms.IntegerField(required=True,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'col-3 mr-4 form-control',
                                       'type': 'number', 'min': '0',
                                       'step': '0.1',
                                       'value': 0
                                    }))
    type = forms.ChoiceField(choices=Supply.Types.choices,
                             required=True,
                             widget=forms.Select(
                                 attrs={
                                     'class': 'col-3 mr-4 custom-select'
                                 }))
    # state = forms.TypedChoiceField(choices=formfields.State, initial='FIXED')




MaterialFormSet = formset_factory(MaterialForm, extra=5)

biomixer_interface/back_end/views.py
import json
import logging
import os.path
from biomixer_interface.settings import STATIC_PATH
from biomixer_interface.net_functions.ip import IP
from django.views import View
from django.shortcuts import render, redirect
import socket
import qrcode
from django.http import HttpResponse, HttpRequest
from .models import *
from .forms import MaterialFormSet, Labels
from biomixer_interface.arduino.machine_cmd import MachineCmd

machine = MachineCmd()

class HomePage(View):
    """
        Home page view
        manages the request for the home page
    """

    def get(self, request):
        """

        :param request:
        :return:
        """
        return render(request, 'home.html', context={})

    def post(self, request):
        """

        :param request:
        :return:
        """
        pass


class LibraryPage(View):
    """
        Home page view
        manages the request for the home page
    """

    def get(self, request):
        """

        :param request:
        :return:
        """
        recipes = []
        recipes_qry_set = Recipe.objects.all()
        for recipe in recipes_qry_set:
            recipes.append({
                "id": recipe.id,
                "name":  recipe.name,
                "creation_date": str(recipe.creation_date),
                "link": "recipe?name=" + recipe.name
            })
        recipes_json = json.dumps(recipes)
        return render(request, 'library.html', context={"recipes": recipes, "recipes_json": recipes_json})

    def post(self, request):
        """

        :param request:
        :return:
        """
        pass


class MixingPage(View):
    """
        Home page view
        manages the request for the home page
    """

    def get(self, request):
        """

        :param request:
        :return:
        """
        return render(request, 'mixing.html', context={})

    def post(self, request):
        """

        :param request:
        :return:
        """
        pass
        # form = MixForm(request.POST)
        # if form.is_valid():


class PreparingPage(View):
    """
        Home page view
        manages the request for the home page
    """

    # if not machine.portIsUsable():
    #    print("[WARNING]: PLEASE CONNECT ARDUINO TO THE RASPBERRY")

    def get(self, request):
        """
        :param request:
        :return:
        """
        formset = MaterialFormSet()
        return render(request, 'preparing.html', context={'form_pack': zip(formset, Labels.options),
                                                          'formset': formset})

    def post(self, request):
        """
        :param request:
        :return:
        """
        formset = MaterialFormSet(request.POST)
        material_list = []
        material_index = []
        value_list = []

        if formset.is_valid():
            n_recipes = Recipe.objects.all().count()+1
            recipe = Recipe.objects.create(name="New_recipe "+str(n_recipes), tag="", img_link="")
            i = 0
            for answer in formset.cleaned_data:
                Supply.objects.create(recipe=recipe, position=i, material=answer['material'],
                                      value=answer['value'], type=answer['type'])
                material_list.append(answer['material'].name)
                value_list.append(answer['value'])
                material_index.append(i+1)
                i += 1
            # new_request = HttpRequest()
            # query  = QuerDict(f'water={value_list[0]}')
            # new_request.path = url('back_end:machine_controller')
            # new_request.GET = query
            # render(request)

            machine.set_values(cmd=machine.CMD_SET_VALUES,
                        d1=value_list[0], d2=value_list[1],
                        d3=value_list[2], d4=value_list[3],
                        d5=value_list[4])
            machine.write()

        else:
            print(formset.errors)

        return render(request, 'mixing.html', context={'materials_and_index': zip(material_list, material_index),
                                                       'materials': material_list,
                                                       'values': value_list})


class QRConnect(View):
    already_visited = True

    def get(self, request):
        if self.already_visited:
            path = os.path.join(STATIC_PATH, 'img')
            print(path)
            host = IP.get_ip()
            ip = socket.gethostbyname(host)
            ip = 'http://' + ip + ':8000'
            img = qrcode.make(ip)
            img.save(path + '/qrip.png', )
            print(img)

        return render(request, 'qrip.html')


class DropZone(View):
    def get(self, request):
        return render(request, 'dzone.html')

    def post(self, request):
        my_file = request.FILES.get('file')
        Doc.objects.create(upload=my_file)
        return HttpResponse('upload')

    @staticmethod
    def success(request):
        return render(request, 'dzone_success.html')


class LiveOutputs(View):
    def txt(self):
        try:
            new_text = machine.read(line=True).decode()
        except Exception as e:
            print(e)
        print(new_text)
        path = os.path.join(STATIC_PATH, 'machine_output/')
        file = open(path + 'output.txt', 'a')
        #file.write("\n")
        file.write(str(new_text))
        file.close()

        with open(path+"output.txt","r") as file:
            for last_line in file:
                pass
        response = HttpResponse()
        response.write("<pre>" + last_line + "</pre>")
        return response


class RecipePage(View):
    def get(self, request):
        name = request.GET.get("name")
        recipe = Recipe.objects.get(name=name)
        supply_qry_set = Supply.objects.filter(recipe=recipe).order_by('position')
        steps_qry_set = Step.objects.filter(recipe_id=recipe)
        supplies = []
        materials = []
        values = []
        for supply in supply_qry_set:
            material = supply.material.name
            materials.append(material)
            values.append(supply.value)
            supplies.append({
                "position": supply.position+1,
                "material": material,
                "value": supply.value,
                "type": supply.type,
            })
        print(recipe, supplies)
        return render(request, template_name="recipe.html", context={"materials": materials,
                                                                     "values": values,
                                                                     "supplies": supplies,
                                                                     "recipe_name": recipe.name,
                                                                     "creation_date": recipe.creation_date})

    def post(self, request):
        pass


class MachineController(View):

    @staticmethod
    def check_values(value_list):
        for i in range(len(value_list)):
            if  value_list[i] is None:
                value_list[i] = 0
        return value_list

    def get(self, request):

        cmd = request.GET.get("cmd")
        water = request.GET.get("water")
        agar = request.GET.get("agar")
        propinate = request.GET.get("propinate")
        glycerin = request.GET.get("glycerin")
        residue = request.GET.get("residue")
        value_list = [water, agar, propinate, glycerin, residue]
        value_list = self.check_values(value_list)
        message = "Get " + str(value_list)
        # print(message)
        if cmd is not None:
            # print("cmd is: "+ cmd)
            if cmd is "0":
                machine.set_values(machine.CMD_START,0,0,0,0,0)
                print(f"Start = {cmd}")
            elif cmd is "1":
                machine.set_values(machine.CMD_STOP,0,0,0,0,0)
                print(f"Stop = {cmd}")
            machine.write()


        return HttpResponse(content=message)

    def post(self, request):
        return HttpResponse(content='POST')

biomixer_interface/back_end/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Flav icon -->
    <link rel="icon" href="{% static 'img/biofabrication_node_identity/logo.svg'   %}"/>
    <link rel="stylesheet" href="../static/fontawesome-free-5.6.3-web/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/bootstrap4-neon-glow.min.css">
    <link rel="stylesheet" href="../static/css/Roboto.css" >
    <link rel="stylesheet" href="{% static 'css/biofabrication_node_identity.css' %}">
    {% block HEAD %}
    {% endblock %}
</head>
<body>
    <!-- Button Menu (move between pages) -->
    <div class="navbar-dark text-white">
        <div class="container">
            <div class="m-3 col-xl-4">
                <a href="{% url 'back_end:home' %}">
                    <img
                            src="{% static 'img/biofabrication_node_identity/Logo_NBD 1.png' %}"
                            style="height: 5em"
                    >
                </a>
            </div>
            <nav class="navbar px-0 navbar-expand-lg navbar-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <!-- <a href="{% url 'back_end:home' %}" class="pl-md-0 p-3 text-light">Home</a> -->
                        <a href="{% url 'back_end:library' %}" class="p-3 text-decoration-none text-light">Library</a>
                        <a href="{% url 'back_end:preparing' %}" class="p-3 text-decoration-none text-light">Prepare a Mix</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    {% block body %}
    {% endblock %}

    {% block footer %}
        <div class="row">
            <div class="container">
                <img class="m-3" src="{% static 'img/biofabrication_node_identity/Logo_NBD_white.png' %}" style="height: 3em">
                <img class="m-3" src="{% static 'img/biofabrication_node_identity/logofabw.svg' %}" style="height: 3em">
            </div>
        </div>
    {% endblock %}
</body>

<script src="../static/js/jquery.js"></script>
<script src="../static/js/popper.min.js"  crossorigin="anonymous"></script>
<script src="../static/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="../static/js/extraFunctions.js"></script>
{% block JS %}

{% endblock %}
</html>

biomixer_interface/back_end/templates/dzone.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Flav icon -->
    <link rel="icon" href="{% static 'img/biomixer.png'   %}"/>
    <link rel="stylesheet" href="../static/fontawesome-free-5.6.3-web/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/bootstrap4-neon-glow.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'dropzone/dist/basic.css' %}">
    <link rel="stylesheet" href="{% static 'dropzone/dist/dropzone.css' %}">
</head>

<body>
    <div class="row">
        <span style="height: 6em"></span>
    </div>
    <div class="container">
        <h1>Upload Zone</h1>
        <p>Upload your file here, you can drag an drop it!</p>
        <!-- DROP ZONE-->
        <form   action="/file-upload"
                class="dropzone"
                id="my-dropzone">

            <div class="fallback">
                <input name="file" type="file" multiple/>
            </div>
            {% csrf_token %}
        </form>
        <br>
        <span style="height: 6em"></span>
        <span id="dzone-submit" class="button btn-success p-2 m-4 rounded-pill" onclick="process()">Subir Archivos</span>
    </div>
</body>
<script src="{% static 'dropzone/dist/dropzone.js' %}"></script>
<script src="{% static 'dropzone/myDzone.js' %}"></script>

</html>

biomixer_interface/back_end/templates/dzone_success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Flav icon -->
    <link rel="icon" href="{% static 'img/biomixer.png'   %}"/>
    <link rel="stylesheet" href="../static/fontawesome-free-5.6.3-web/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/bootstrap4-neon-glow.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>

<body>
<div class="row">
    <span style="height: 6em"></span>
</div>
<div class="container">
   <h1> Your files were uploaded with success</h1>
</div>
</body>

</html>

biomixer_interface/back_end/templates/home.html
{% extends 'base.html' %}

{% block HEAD %}
    <title> Bio Mixer</title>
    <link rel="stylesheet" href="../static/css/modifiers.css">
    <link rel="stylesheet" href="../static/dropzone/dist/basic.css">
    <link rel="stylesheet" href="../static/dropzone/dist/dropzone.css">
{% endblock %}
{%  block body%}

    <!-- Main Page -->
    <div class="jumbotron bg-transparent mb-0 radius-0">
        <div class="container">
            <div class="row">
                <div class="col-xl-8">
                    <div class="row">
                        <div class="col-xl-3">
                            <h1 class="display-2">Bio Mixe<span class="vim-caret">r</span></h1>
                        </div>
                    </div>
                    <!-- Title -->
                    <div class="lead mb-3 text-mono text-success">Bio Mixer interface 1.1</div>
                    <!-- Description -->
                    <div class="text-darkgrey text-mono my-2">Welcome to Bio Mixer. A new experience in Material Fabrication</div>
                    <!-- Client -->
                    <p class="text-grey text-spacey">
                        FabLab Uchile Prototype
                    </p>

                    <div class="text-mono">
                        <!-- Button 1 -->
                        <a href="{% url 'back_end:library' %}"
                           title="Download Theme"
                           class="btn btn-fab-green btn-shadow px-3 my-2 ml-0 text-left">
                            Check Material Library
                        </a>
                        <!-- Button 2 -->
                        <a href="{% url 'back_end:preparing' %}"
                           class="btn btn-fab-orange btn-shadow px-3 my-2 ml-0 ml-sm-1 text-left">
                            Preparing a Mix
                        </a>

                        <!-- Button 3 -->
                        <a id="new_library" onclick="makeVisible('dropzone')"
                           class="btn btn-fab-purple btn-shadow px-3 my-2 ml-0 ml-sm-1 text-left">
                            Import a Recipe
                        </a>
                    </div>
                </div>
                <div class="col-xl-4">
                    <div id="dropzone" class="container hidden_element">
                        <h1>Upload Zone</h1>
                        <p>Upload your file here, you can drag an drop it!</p>
                        <!-- DROP ZONE-->
                        <form   action="/file-upload"
                                class="dropzone"
                                id="my-dropzone">

                            <div class="fallback">
                                <input name="file" type="file" multiple/>
                            </div>
                            {% csrf_token %}
                        </form>
                        <br>
                        <span style="height: 6em"></span>
                        <span id="dzone-submit" class="button btn-success p-2 m-4 rounded-pill" onclick="process()">Subir Archivos</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container py-5">
        <h1></h1>
        <!-- Credits to the HTML template form -->
        <!--
        <p>Thank you for downloading this theme. If you have trouble or find a bug, please open an issue on GitHub:<br>
          <a href="https://github.com/HackerThemes/theme-machine">https://github.com/HackerThemes/theme-machine</a></p>
        -->
        <!-- Developer info-->
        <p class ="text-darkgrey text-mono my-2">Created by Marcelo Becerra A. consulting to marcelo.becerra@ug.uchile.cl</p>
    </div>
{% endblock %}

{% block JS %}
    <script src="../static/dropzone/dist/dropzone.js"></script>
    <script src="../static/dropzone/myDzone.js"></script>
    <script src="../static/js/extraFunctions.js"></script>
{% endblock %}

biomixer_interface/back_end/templates/library.html
{% extends 'base.html' %}
{% load static %}

{% block HEAD %}
    <link rel="stylesheet" href="../static/css/dataTables.bootstrap4.min.css">
{% endblock %}
{% block body %}
    <div class="container py-5 mb5">
        <!-- Title -->
        <h1 class="mb-5">Material Library</h1>
        <!-- Category and Search Tab -->
        <table id="recipes_table" class="table" data-height="20">
                    <thead class="thead-light">
                        <tr>
                            <th data-field="id" class="text-light" scope="col">#</th>
                            <th data-field="name" class="text-light" scope="col">Material</th>
                            <th data-field="creation_date" class="text-light" scope="col">Creation Date</th>
                            <th class="text-light" scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for recipe in recipes %}
                        <tr>
                            <th scope="row">{{ recipe.id }}</th>
                            <td>
                                <a href="{% url 'back_end:home' %}{{ recipe.link }}">
                                    {{ recipe.name }}
                                </a>
                            </td>
                            <td>
                            <span class="font-italic">
                                {{ recipe.creation_date }}
                            </span>
                            </td>
                            <td>
                                <a href="#" class="btn btn-sm btn-primary my-1 my-sm-0">
                                    <span class="fas fa-edit mr-1"></span>
                                    Edit</a>
                                <a href="#" class="btn btn-sm btn-danger my-1 my-sm-0">
                                    <span class="fas fa-trash mr-1"></span>
                                    Visualize</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
    </div>
{% endblock %}

{% block JS %}
    <script src="../static/js/jquery.dataTables.min.js"></script>
    <script src="../static/js/dataTables.bootstrap4.min.js"></script>
    <script>
        console.log("RECIPES");
        let my_data = JSON.parse('{{ recipes_json | escapejs }}');
        let table = document.getElementById("recipes_table");
        $(document).ready(function() {
            $('#recipes_table').DataTable();
        } );
    </script>
{% endblock %}

biomixer_interface/back_end/templates/mixing.html
{% extends 'base.html' %}
{% load static %}

{% block HEAD %}
    <link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/figures.css' %}">
{% endblock %}

{% block body %}
<div id="dashboard" class="container shadow">
    <div id="first-row" class="row">
        <div id="pipeline" class="container border-info">
            <h5 class="mybadge mybadge-primary mybadge-pill"> Avance del Proceso (Estado)</h5>
            <div class="row mt-4">
                <div class="col-10">
                    <ul id="progressbar">
                        {% for material, index in materials_and_index %}
                        <li class="inactive" id="m{{ index }}"><strong>{{ material }}</strong></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg">
                    <button id="toggle" class="btn btn-fab-orange btn-shadow" onclick="linearToggleProgressbar()">
                        Toggle Material
                    </button>
                    <button id="start-stop" class="btn btn-fab-green btn-shadow" onclick="switchStartStop('start-stop')">
                        Start
                    </button>
                </div>
            </div>

        </div>
    </div>

    <div id="second-row" class="row">
        <div id="security-status" class="col-6 container">
            <h5 class="mybadge mybadge-primary mybadge-pill"> Indicadores de Seguridad</h5>
            <div class="row mt-4">
                <label class="col-xl-4">Posición de la Olla</label>
                <div class="col-2">
                    <img src="../static/img/mixing/check.svg" style="width: 30px">
                </div>
            </div>
        </div>
        <div id="space" class="col-2 container">
            <span style="width: 5em"></span>
        </div>
        <div id="composition" class="col-4 container">
            <h5 class="mybadge mybadge-primary mybadge-pill"> Composición del Material</h5>
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>

    <div id="third-row" class="row">
        <div id="" class="col-12 container align-self-lg-start">
            <h4 class="mybadge mybadge-primary mybadge-pill"> Machine raw input</h4>
            <div class="bg-dark">
                <div class="text-mono" style="width: 100%; height: 10em" >
                    <p id="machine_output" class="text-white"></p>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

{% block JS %}
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.js"></script>
        <script id="Sample">
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [
                        {% for material in materials %}
                            '{{ material }}',
                        {% endfor %}
                    ],
                    datasets: [{
                        label: '# of Votes',
                        data: [
                            {% for value in values %}
                                {{ value }},
                            {% endfor %}
                        ],
                        backgroundColor: [
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(93, 102, 255, 1)',
                        ],
                        borderColor: [
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(153, 102, 255, 1)',
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        x: {
                            beginAtZero: true
                        }
                    }
                }
            });

    </script>
    <script src="../static/js/extraFunctions.js"></script>
    <!-- Load Content -->
    <script>
        setInterval(loadDoc, 1000);

        function loadDoc() {
            const xhttp = new XMLHttpRequest();
            xhttp.onload = function() {
                document.getElementById("machine_output").innerHTML =
                    this.responseText;
            }
            xhttp.open("GET", "{% url 'back_end:machine_output' %}");
            xhttp.send();
        }

    </script>
{% endblock %}